name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '36 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch latest data
      run: |-
        curl https://overpass-api.de/api/interpreter?data=%2F*%0AThis%20has%20been%20generated%20by%20the%20overpass-turbo%20wizard.%0AThe%20original%20search%20was%3A%0A%E2%80%9Camenity%3Dpost_box%E2%80%9D%0A*%2F%0A%5Bout%3Ajson%5D%5Btimeout%3A25%5D%3B%0A%2F%2F%20gather%20results%0A%28%0A%20%20%2F%2F%20query%20part%20for%3A%20%E2%80%9Camenity%3Dpost_box%E2%80%9D%0A%20%20node%5B%22amenity%22%3D%22post_box%22%5D%3B%0A%20%20way%5B%22amenity%22%3D%22post_box%22%5D%3B%0A%20%20relation%5B%22amenity%22%3D%22post_box%22%5D%3B%0A%29%3B%0A%2F%2F%20print%20results%0Aout%20body%3B%0A%3E%3B%0Aout%20skel%20qt%3B | jq . > states.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |-
        pip install -r requirements.txt
    - name: Build SQLite database
      run: python build_database.py
    - name: Deploy database to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |-
        datasette publish vercel cdc.db \
          --title "CDC vaccination numbers" \
          --about "simonw/cdc-vaccination-history" \
          --about_url "https://github.com/simonw/cdc-vaccination-history" \
          --source "CDC" \
          --source_url "https://covid.cdc.gov/covid-data-tracker/#vaccinations" \
          --install datasette-vega \
          --install datasette-graphql \
          --project cdc-vaccination-history \
          --token $VERCEL_TOKEN \
          --extra-options "--setting sql_time_limit_ms 5000 --facet_time_limit_ms 3000"


