name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '45 13 * * 0'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3 
      with:
        fetch-depth: 0
    - name: Fetch latest data
      run: |-
        curl https://overpass-api.de/api/interpreter?data=%5Bout%3Ajson%5D%5Btimeout%3A25000%5D%3B%0A%2F%2F%20gather%20results%0A%28%0A%20%20%2F%2F%20query%20part%20for%3A%20%E2%80%9Camenity%3Dpost_box%E2%80%9D%0A%20%20node%5B%22amenity%22%3D%22post_box%22%5D%3B%0A%20%20way%5B%22amenity%22%3D%22post_box%22%5D%3B%0A%20%20relation%5B%22amenity%22%3D%22post_box%22%5D%3B%0A%29%3B%0A%2F%2F%20print%20results%0Aout%20body%3B%0A%3E%3B%0Aout%20skel%20qt%3B | jq . > post_boxes.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
    
